driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: fedora-20
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
    run_list:
      - recipe[yum-epel]
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8090}]
        - ["forwarded_port", {guest: 443, host: 4433}]
  - name: centos-7.0
    run_list:
      - recipe[yum-epel]
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8091}]
        - ["forwarded_port", {guest: 443, host: 4434}]

suites:
  - name: munin-client
    run_list:
      - recipe[munin::client]
  - name: munin-server
    run_list:
      - recipe[munin::server]
      - role[munin_server]
    attributes:
      munin:
        server_auth_method: none
#  - name: server_apache
#    run_list:
#      - recipe[munin::server_apache]
#  - name: server_nginx
#    run_list:
#      - recipe[munin::server_nginx]

data_bags_path: test/integration/data_bags/
roles_path: test/integration/roles/
environments_path: test/integration/environments
